### ISSUE TITLE
[Question] blazor 3.2 preview 1

### ISSUE THREAD

**Issue by ofrades** [Blazored/Localisation#17]
In this line: `host.InitializeBlazoredLocalization();`
I am getting this error:
```
'WebAssemblyHost' does not contain a definition for 'InitializeBlazoredLocalization' and no accessible extension method 'InitializeBlazoredLocalization' accepting a first argument of type 'WebAssemblyHost' could be found (are you missing a using directive or an assembly reference?)
```

I am using your settings but I have this error. Do you have any idea why?

**Comment by ofrades** [comment]
I am also getting `GET http://localhost:64590/_content/Blazored.Localisation/blazored-localisation.js 404 (Not Found)`

**Comment by chrissainty** [comment]
The first error you're getting looks like a missing using statement. Are you sure everything is referenced correctly?

The second error is similar in that you would get this is there was error referencing the NuGet package.

As you're seeing both of these I would try removing the package and doing a clean of your solution - perhaps even delete your bin and obj folders. Once you've done that reinstall the package and try another built. It could be an odd caching issue, it's happened before.

**Comment by mattgenious** [comment]
Could be this issue?
https://stackoverflow.com/questions/58862932/blazor-server-static-files-dont-link-in-non-dev-environments

**Comment by ofrades** [comment]
The first error is the main problem. I have `using Blazored.Localisation;` on top; I have `builder.Services.AddBlazoredLocalisation();`and no error; but with `host.InitializeBlazoredLocalization();` he complains: `'WebAssemblyHost' does not contain a definition for 'InitializeBlazoredLocalization' and no accessible extension method 'InitializeBlazoredLocalization' accepting a first argument of type 'WebAssemblyHost' could be found (are you missing a using directive or an assembly reference?)`

I have deleted obj and bin folders, installed the package again, but with same results.

**Comment by mattgenious** [comment]
are you on visual studio 16.5.0 Preview 2.0 and are your packages updated to v3.2.0-preview1.2073.1 and is Blazored.Localisation updated to version 2.0?
Also, may I see your Main method in Program.cs? (just to see how you prepare and build the host)

**Comment by ofrades** [comment]
Thanks mattgenious. I was using 1.1.1 and updating to 2.0.0 solved the issue. I am using vscode-insiders and to install NuGet packages I am using NuGet Gallery extension. The problem was that this extension was giving me wrongly the version 1.1.1 as the latest.
