### ISSUE TITLE
Localization vs Localisation

### ISSUE THREAD

**Issue by MaxMommersteeg** [Blazored/Localisation#18]
For wiring up Blazored.Localisation in Program.cs there is:
`builder.Services.AddBlazoredLocalisation();`

And

`host.InitializeBlazoredLocalization();`

locali**s**ation (British English) vs locali**z**ation (American English). Shouldn't we pick one?

**Comment by chrissainty** [comment]
Agreed, that is a bad one to slip through, especially considering what this library does. In hindsight, I wish I'd just gone the American English spelling for everything (I'm British BTW) as it's probably more common. So the pick would be _Localization_.

As this will be a breaking change I don't want to bump the version number just for this, but I'd be happy to take a PR and release once we have a bit more to go with.

**Comment by MaxMommersteeg** [comment]
Thanks for your reply.

I understand that this will not be fixed very soon since it will break the api. This issue is mainly here for traceability.

**Comment by TechCitySouth** [comment]
I'm just now trying to implement Blazored Localisation and hitting this error:
On host.InitializeBlazoredLocalization(); I get "WebAssemblyHost' does not contain a definition for 'InitializeBlazoredLocalization' and the best extension method overload WebAssemblyHostExtensions.InitializeBlazoredLocalization(WebAssemblyHost)' requires a receiver of type 'WebAssemblyHost'

On host.InitializeBlazoredLocalisation(); I get
'WebAssemblyHost' does not contain a definition for 'InitializeBlazoredLocalisation' and no accessible extension method 'InitializeBlazoredLocalisation' accepting a first argument of type 'WebAssemblyHost' could be found (are you missing a using directive or an assembly reference?)	

Is there a way to make this work or do I need to wait until it's fixed?

**Comment by chrissainty** [comment]
@TechCitySouth Could you raise your problem in a separate issue? This one is for tracking the mismatch in naming.

**Comment by chrissainty** [comment]
This library is now obsolete. Please use the native functionality in Blazor.
