### ISSUE TITLE
Language setting

### ISSUE THREAD

**Issue by vignatov** [Blazored/Localisation#3]
Is it possible to modify the library to make the language selectable inside the app? Relying on browser culture is not always the best way.

**Comment by chrissainty** [comment]
Yes, definitely. When you say in the app do you mean from a user point of view or a developer?

**Comment by chrissainty** [comment]
Anything is possible with enough effort 😄. Do you have an idea of how you would want this to work in terms of developer experience?

**Comment by vignatov** [comment]
I believe it should instead of getting the language from the browser get it from local storage. 
Ideally the library would provide a list of existing language for the front end to display a dropdown box, user selects a language and the library saves it in the local storage.
So, as far as I can see 4 functions:

1. GetSupportedCultures(). Returns List of cultures.
2. GetCurrentCulture(). Returns currently active culture.
3. SaveCulture(). Saves new selection.
4. ResetToDefault(). Erases settings from the local storage (when users logs out, for example).

**Comment by chrissainty** [comment]
So are you suggesting you don't want any automatic detection of the users' locale?

**Comment by vignatov** [comment]
I think automatic detection is not reliable, it can stay as optional or for picking a default language on first run, but it has to allow manual overriding.
Depending on user settings some of the browsers return always the same current location (iPhone Safari for example) others return culture basing on your current location. It leads to the situation when user complains that they see English version on their phone and Japanese version on desktop. If I could manually override this basing on the user initial settings it would not be a problem.
There are even weirder issues with auto culture detection. In the UK there are 4 regions England, Wales, Scotland and Northern Ireland, they have their local languages although the main language is English. However, the culture system supports those local languages and localises certain names (like if you get Pound Sterling in English, in Welsh it is Punt Prydain). When the site requests localised name of the currency it returns it in Welsh if you had your default location in Wales.

**Comment by chrissainty** [comment]
That all makes sense @vignatov. Would you would be willing to put a PR together based on what you've said? If not I'll add it to my todo.

**Comment by chrissainty** [comment]
I've decided to close this issue, I just haven't got the time to get to it and there are some localisation bits coming out of the box with Blazor soon which may deal with the concerns raised here.
