### ISSUE TITLE
Culture is being reset after state gets changed

### ISSUE THREAD

**Issue by Franklin89** [Blazored/Localisation#5]
Hi,

I am using this approach for setting the culture in my blazor app. I have a `DateTime` property that is bound to an input field. The initial load is with the correct Culture. If I then change the value of the input field the Culture gets reset to the default culture and the date is formatted incorrectly.

Any idea how to solve that?

**Comment by chrissainty** [comment]
Is the culture being reset or is the format of the date just getting screwed up?

If you place the following code on your page somewhere

`<p>Current Culture: <strong>@CultureInfo.CurrentUICulture.DisplayName</strong></p>`

This will print out the current culture, can you do that and let me know if its changed?

**Comment by Franklin89** [comment]
I just tested it. The culture gets reset to `Current Culture: Invariant Language (Invariant Country)`
I sent you a PR with a fix that sets the `DefaultThreadCurrentCulture`. With that set it works as expected.
